# core/rules_generated.py
# =============================================================================
# AUTO-GENERATED by build_rules.py — НЕ РЕДАГУВАТИ РУКАМИ
# Джерела: antifrod_trade_terms.json + antifrod_reviews.json + antifrod_concepts.json
# Policy:
#   - trade_terms  → merchant instruction layer, severity as-is
#   - reviews      → capped at SOFT (review_only=True), no direct BLOCK
#   - concepts     → base regex atoms, deduped + merged
#   - short ambiguous atoms → SOFT, require LLM co-eval
# =============================================================================
"""
Розширений реєстр правил v2.0.

Нові правила додані поверх базового rules.py:
  - HARD/SOFT/WARN/SAFE шари збережені
  - review_only правила мають окремий review_only=True прапор
  - suppress_hard поля заповнені де є explicit SAFE кандидати

Додавання нових правил:
  1. Оновіть antifrod_*.json
  2. Запустіть build_rules.py → rules_generated.py
  3. Скопіюйте нові RegexRule в production rules.py
"""
from __future__ import annotations

import re
from dataclasses import dataclass

HARD_CONFIRM_REQUIRED = frozenset({"EXTERNAL_LINK", "TRIANGLE"})
HARD_DIRECT_BLOCK     = frozenset({"NO_COMMENTS", "CASINO"})


@dataclass(slots=True)
class RegexRule:
    id:            str
    category:      str
    pattern:       re.Pattern
    weight:        int
    action:        str
    description:   str
    suppress_hard: frozenset = frozenset()
    review_only:   bool      = False



HARD_RULES: list[RegexRule] = [
    RegexRule(
        "GEN_H01_EXTERNAL",
        "EXTERNAL_LINK",
        re.compile(
            r"(?:t\.me)|(?:telegram\.me)|(?:@\w{4,})|(?:\bтг\b)|(?:телег(а|рам))|(?:вайбер)|(?:viber:)|(?:whatsapp)|(?:watsap)|(?:\bлс\b.{0,10}(до|перед|оплат))|(?:(пишіть|write|contact).{0,25}(telegram|tg|viber|whatsapp|signal|телеграм|вайбер))",
            re.IGNORECASE,
        ),
        100,
        "BLOCK",
        "Виведення угоди в зовнішній месенджер — перший крок скаму: поза контролем платформи мерчант може дав",
        suppress_hard=frozenset({'не пишіть у тг', 'в месенджери не переходжу', 'тільки чат біржі', 'не виходжу за межі платформи'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_H02_TRIANGLE",
        "TRIANGLE",
        re.compile(
            r"(?:дроп(и|ів|овод|ер|ів)?)|(?:треугол)|(?:трикутник)|(?:чуж[аіо].{0,5}(карт|рахун))|(?:від.{0,10}(знайом|друг|родич))|(?:карта.{0,15}(знайом|друг|дружин|брат|сестр))|(?:карта.{0,15}(знайом|друг|дружин|брат|сестр|родич))|(?:чуж[аіою].{0,10}(карт|рахун|особ))|(?:переказ.{0,15}від.{0,15}(знайом|друг))|(?:від\sіншої\s(особи|людини))|(?:дроп[иів]?.{0,10}(вітаються|ок|ok|прийма|можна|допускаються|норм|welcome|allowed))|(?:лев[иіо].{0,5}(реквіз|рекв))|(?:чуж[іаою].{0,5}(реквіз|рахун|ібан|картк))|(?:реквізити.{0,10}(не\s*мо[їя]|від\s*інш|чужі))",
            re.IGNORECASE,
        ),
        100,
        "BLOCK",
        "Дроп = підставна особа для прийому/відправки коштів. Трикутник = схема де мерчант дає реквізити не с",
        suppress_hard=frozenset({'без дропів', 'дропи заборонені', 'дроп не приймаю', 'дроп відмовлю'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_H03_NO_COMME",
        "NO_COMMENTS",
        re.compile(
            r"(?:без.{0,10}(коментар|призначен|комент))|(?:пуст(е|о).{0,5}(поле|призначен))|(?:нічого.{0,5}(не\s*)?пиш)|(?:не.{0,10}вказуйте.{0,10}призначен)|(?:поле.{0,10}(залиш|лиш).{0,5}пустим)|(?:\bб/к\b)|(?:no.?comment)|(?:пуст(е|е).{0,10}(поле|призначен))",
            re.IGNORECASE,
        ),
        100,
        "BLOCK",
        "Заборона коментарів у призначенні переказу — класичний спосіб приховати зв'язок між P2P угодою і бан",
        suppress_hard=frozenset(),
        review_only=False,
    ),
    RegexRule(
        "GEN_H04_CASINO",
        "CASINO",
        re.compile(
            r"(?:казино|casino|казик)|(?:гембл[аиу]|gambling)|(?:букмекер|bookie)|(?:беттинг|betting)|(?:\bбетк[аиу]\b)|(?:проц\b|процесинг|processing)|(?:агрегатор)|(?:1x.?bet|melbet|mostbet|betway|parimatch|fonbet)|(?:казино)|(?:casino)|(?:казик)|(?:1x.?bet)|(?:melbet)|(?:mostbet)|(?:betway)|(?:parimatch)|(?:fonbet)|(?:покер)|(?:poker)|(?:букмекер)|(?:bookie)|(?:ставки.{0,10}(на\s*)?спорт)|(?:гральн)|(?:gambling)|(?:гембл)|(?:беттинг)|(?:betting)|(?:процесинг)|(?:processing)|(?:проц\b)|(?:бетк[аиу])|(?:\bбук\b)|(?:ставки.{0,10}(спорт|онлайн|прийма))",
            re.IGNORECASE,
        ),
        100,
        "BLOCK",
        "Усі ці сервіси заборонені або обмежені більшістю Ukrainian банків та P2P платформ. Участь у їх проце",
        suppress_hard=frozenset({'не беру казино трафік', 'без гемблінгу', 'без беттингу'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_S02_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:обнал(ичк|ьн|ьщик|ьник)?)|(?:фінмон|фінансов.{0,5}моніторинг)|(?:aml|anti.?money)|(?:заморозк)|(?:серяк|сірак)|(?:грязн|брудн.{0,5}(гроші|кошти))|(?:відмивання)|(?:мутн(ий|а|ка))|(?:фінмон)|(?:фінансов.{0,5}моніторинг)|(?:aml)|(?:anti.?money)|(?:блокуван.{0,10}(рахунк|картк))|(?:сір[аі].{0,10}(схем|гроші))|(?:обнал)|(?:обнал(ичк|ьн|ьщик|ичиван)?\b)|(?:грязн)|(?:брудн.{0,5}(гроші|кошти))|(?:сір[аі].{0,5}(схем|гроші|кошти))|(?:dirty.{0,5}money)|(?:черн.{0,5}деньг)|(?:серы.{0,5}деньг)",
            re.IGNORECASE,
        ),
        100,
        "BLOCK",
        "Пряма або прихована ознака участі у відмиванні коштів або роботі з коштами незаконного походження.",
        suppress_hard=frozenset({'без обналу', 'не обнал', 'без сірих схем', 'чисті кошти тільки'}),
        review_only=False,
    ),
]

SOFT_RULES: list[RegexRule] = [
    RegexRule(
        "GEN_S01_CHARGEBA",
        "CHARGEBACK",
        re.compile(
            r"(?:\bреф(анд)?\b)|(?:чардж(бек|нув|ував)?)|(?:charge.?back)|(?:\bдисп(ут)?\b)|(?:dispute)|(?:апел(ка|яці|яха|юха)?)|(?:refund)|(?:чардж)|(?:chargeback)|(?:реф(анд)?\b)|(?:диспут)|(?:dispute.{0,15}(відкри|подам|open))|(?:відкрию.{0,10}спір)|(?:повернення.{0,10}(через\s*банк|коштів\s*через))",
            re.IGNORECASE,
        ),
        40,
        "NEEDS_LLM",
        "Chargeback та refund у P2P — класичний фінансовий скам: отримав крипту, повернув переказ через банк.",
        suppress_hard=frozenset({'без чарджів', 'чардж не роблю', 'захист від рефанду'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_S03_ANONYMOU",
        "ANONYMOUS",
        re.compile(
            r"(?:анонімн)|(?:anonymous)|(?:без.{0,10}(перевірк|питань|kyc|kyk|документ|верифікац))|(?:no.{0,5}(questions|kyc|id|checks))|(?:cash.?in)|(?:термінал.{0,10}(оплат|поповнен|готівк))|(?:без.{0,10}(перевірк|питань|kyk|kyc|документ|верифікац))|(?:no.{0,5}(questions|kyc|id))|(?:термінал.{0,10}(оплат|поповнен))",
            re.IGNORECASE,
        ),
        30,
        "NEEDS_LLM",
        "Пропозиція угоди без ідентифікації — обхід AML/KYC вимог, типово для дропів та відмивання.",
        suppress_hard=frozenset({"верифікація обов'язкова", 'тільки верифіковані'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_S04_MIDDLEMA",
        "MIDDLEMAN",
        re.compile(
            r"(?:посередник|посеред\b|посред(ник)?)|(?:номінал(ьн)?|номік)|(?:прокладка)|(?:middleman|nominee)|(?:транзит.{0,10}(рахунок|кошти))|(?:посередник)|(?:номінал)|(?:через.{0,10}посередника)|(?:middleman)|(?:nominee)|(?:номік)|(?:посеред\b)",
            re.IGNORECASE,
        ),
        40,
        "NEEDS_LLM",
        "Використання посередника або номінального власника приховує реального бенефіціара — типово для струк",
        suppress_hard=frozenset({'без посередників', 'без номіналів', 'прямий переказ'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_S05_CHAT_FIR",
        "CHAT_FIRST",
        re.compile(
            r"(?:пишіть?.{0,15}(до оплат|перед|спочатку))|(?:написати?.{0,15}(до|перед).{0,10}оплат)|(?:write.{0,15}(before|first))|(?:contact.{0,10}(me\s*)?before)|(?:\bлс\b.{0,10}(до|перед))|(?:повідомте.{0,5}мене.{0,5}перед)|(?:написати.{0,15}(до|перед))|(?:лс.{0,10}(до|перед|оплат))",
            re.IGNORECASE,
        ),
        30,
        "NEEDS_LLM",
        "Вимога контакту поза чатом до угоди — типовий крок виведення з платформи або інструктаж дропової схе",
        suppress_hard=frozenset({'не пишіть до оплати', 'не потрібно писати перед'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_S06_SUSPICIO",
        "SUSPICIOUS_BIZ",
        re.compile(
            r"(?:фоп.{0,10}(оплат|рахун))|(?:рахунок.{0,10}фоп)|(?:iban.{0,10}фоп)|(?:рахунок.{0,10}підприємц)|(?:бізнес.{0,10}рахунок)",
            re.IGNORECASE,
        ),
        40,
        "NEEDS_LLM",
        "Оплата на бізнес-рахунок у P2P — нетипова і ризикована, може бути прикриттям легалізації. Але деякі ",
        suppress_hard=frozenset(),
        review_only=False,
    ),
    RegexRule(
        "GEN_S07_APPEAL_P",
        "APPEAL_PRESSURE",
        re.compile(
            r"(?:апел(яці|яцію|яцій|к[ауи]))|(?:відкри(ю|ємо).{0,15}(апел|спір|суперечку|диспут))|(?:скарг)|(?:поскаржусь)|(?:appeal)|(?:report\s+you)|(?:dispute.{0,10}(open|will|відкри))",
            re.IGNORECASE,
        ),
        30,
        "NEEDS_LLM",
        "Погроза апеляцією як тиск — типовий прийом шахрая щоб змусити відпустити кошти без виконання умов.",
        suppress_hard=frozenset(),
        review_only=False,
    ),
    RegexRule(
        "GEN_S08_THIRD_PA",
        "THIRD_PARTY_HINT",
        re.compile(
            r"(?:третіх.{0,10}осіб)|(?:3.{0,5}особ)|(?:third.{0,5}part)|(?:від.{0,10}інших.{0,10}осіб)",
            re.IGNORECASE,
        ),
        20,
        "NEEDS_LLM",
        "Двозначна фраза — може бути заборона (SAFE) або дозвіл (HARD). LLM повинен оцінити контекст.",
        suppress_hard=frozenset(),
        review_only=False,
    ),
    RegexRule(
        "GEN_H05_TRIANGLE",
        "TRIANGLE",
        re.compile(
            r"(?:треугол)|(?:трикутник)|(?:треуг\b)|(?:triangle.{0,10}scam)",
            re.IGNORECASE,
        ),
        100,
        "NEEDS_LLM",
        "Назва конкретної схеми відмивання через P2P. Відгук з цим словом майже завжди означає реальну скаргу",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S09_TRIANGLE",
        "TRIANGLE",
        re.compile(
            r"дроп(и|ів|овод|ер|ів)?\b",
            re.IGNORECASE,
        ),
        100,
        "NEEDS_LLM",
        "Дроп у негативному відгуку = підозра що мерчант використовує підставних осіб для переказів.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_H06_TRIANGLE",
        "TRIANGLE",
        re.compile(
            r"(?:дроповод)|(?:дроп.?вод\b)",
            re.IGNORECASE,
        ),
        100,
        "NEEDS_LLM",
        "Дроповод = організатор дроп-мережі. Назва ролі в P2P-злочинній схемі.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_H07_TRIANGLE",
        "TRIANGLE",
        re.compile(
            r"(?:чуж[аяіо].{0,5}(карт|рахун|реквіз|картк))|(?:карта.{0,10}не.{0,5}(його|моя|своя))|(?:рахунок.{0,10}не.{0,5}(його|мій))|(?:лев[иіо].{0,5}(реквіз|рекв))",
            re.IGNORECASE,
        ),
        100,
        "NEEDS_LLM",
        "Конкретна ознака дропа — переказ на рахунок що не належить мерчанту.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S10_CASINO",
        "CASINO",
        re.compile(
            r"(?:\bпроц\b)|(?:процес(инг|с\b))|(?:processing\b)",
            re.IGNORECASE,
        ),
        100,
        "NEEDS_LLM",
        "Скорочений сленг для processing — ознака що мерчант займається обробкою платежів для high-risk бізне",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_H08_CASINO",
        "CASINO",
        re.compile(
            r"(?:гембл[аиу])|(?:гемба\b)|(?:gambling)|(?:казик)|(?:казін[оу].{0,10}(трафік|схем))",
            re.IGNORECASE,
        ),
        100,
        "NEEDS_LLM",
        "Сленгова назва гемблінг-бізнесу. Якщо у відгуку — підтверджує що мерчант пов'язаний з казино.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S11_CASINO",
        "CASINO",
        re.compile(
            r"(?:\bбук(а|ач)?\b)|(?:bookie)|(?:беттинг)|(?:бетк[аиу])",
            re.IGNORECASE,
        ),
        100,
        "NEEDS_LLM",
        "Сленг букмекера або беттинг-бізнесу. Двозначне — може бути контекст і без схеми.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S12_CHARGEBA",
        "CHARGEBACK",
        re.compile(
            r"(?:\bреф(анд)?\b)|(?:refund)|(?:реф.{0,15}(банк|апел|схем|через))",
            re.IGNORECASE,
        ),
        40,
        "NEEDS_LLM",
        "Рефанд через банк після P2P = класична схема шахрайства (отримав крипту, скасував переказ).",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S13_CHARGEBA",
        "CHARGEBACK",
        re.compile(
            r"(?:чардж(бек|нув|ував)?)|(?:chargeback)|(?:charge.?back)|(?:зчарджив)",
            re.IGNORECASE,
        ),
        40,
        "NEEDS_LLM",
        "Chargeback = повернення через банк після отриманої крипти. У відгуках майже завжди скарга на реальни",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S14_APPEAL_P",
        "APPEAL_PRESSURE",
        re.compile(
            r"(?:\bдисп(ут|утував)?\b)|(?:dispute)|(?:апел(ка|яція|яха|юха|ювання)?\b)",
            re.IGNORECASE,
        ),
        30,
        "NEEDS_LLM",
        "Диспут як інструмент тиску або як результат конфлікту — маркер проблемної угоди.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S15_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:мутк[аиу])|(?:мутн(ий|а|о))|(?:мутняк)|(?:темн(ий|а|о|як))|(?:темна.{0,5}(схем|тем))",
            re.IGNORECASE,
        ),
        50,
        "NEEDS_LLM",
        "Жаргонне визначення підозрілої/незрозумілої/нечесної операції. У відгуках = попередження від досвідч",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S16_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:серяк)|(?:сірак)|(?:сір[аі].{0,5}(схем|гроші|трафік|контор|тем))|(?:gray.{0,5}scheme)|(?:grey.{0,5}money)",
            re.IGNORECASE,
        ),
        50,
        "NEEDS_LLM",
        "Жаргонна назва напівлегальних або нелегальних фінансових операцій.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_H09_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:обнальщик)|(?:обнальн)|(?:обнал(ичк|ьник)?\b)",
            re.IGNORECASE,
        ),
        50,
        "NEEDS_LLM",
        "Прямий опис ролі у незаконному обналічуванні коштів.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S17_MIDDLEMA",
        "MIDDLEMAN",
        re.compile(
            r"(?:посеред(ник)?\b)|(?:посред(ник)?\b)|(?:номік)|(?:номінал\b)|(?:прокладка)|(?:middleman)",
            re.IGNORECASE,
        ),
        40,
        "NEEDS_LLM",
        "Наявність посередника у P2P = прихований бенефіціар, типово для відмивання.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S18_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:скам(ер|ував)?)|(?:scam(mer)?)|(?:кинув)|(?:кидало)|(?:розвів)|(?:шахрай)|(?:фейк.{0,5}(мерч|акаун))|(?:розвод)",
            re.IGNORECASE,
        ),
        50,
        "NEEDS_LLM",
        "Пряме звинувачення у шахрайстві у відгуку — дуже важливий сигнал.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S19_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:заморозив)|(?:заморозил[иа])|(?:заморозк)|(?:заблокував)|(?:заблокувал[иа])|(?:freeze)|(?:blocked.{0,10}account)|(?:рахунок.{0,5}заморожен)",
            re.IGNORECASE,
        ),
        50,
        "NEEDS_LLM",
        "Заморозка рахунку після угоди = ознака що кошти мали кримінальне походження або банк їх ідентифікува",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_S20_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:лев[аяиу]к)|(?:лів[аяиу]к)|(?:лів(а|ий|ій).{0,5}(схем|тем|трафік|мерч))|(?:лева.{0,5}(схем|тем))",
            re.IGNORECASE,
        ),
        50,
        "NEEDS_LLM",
        "Жаргонне позначення нелегальної/тіньової операції або мерчанта.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_H10_FINCRIME",
        "FINCRIME",
        re.compile(
            r"(?:грязн)|(?:брудн.{0,5}(гроші|кошти|трафік))|(?:dirty.{0,5}money)|(?:грязь)",
            re.IGNORECASE,
        ),
        50,
        "NEEDS_LLM",
        "Пряма назва коштів злочинного походження у відгуках.",
        suppress_hard=frozenset(),
        review_only=True,  # review-only signal
    ),
]

WARN_RULES: list[RegexRule] = [
    RegexRule(
        "GEN_W01_RECEIPT_",
        "RECEIPT_REQUIRED",
        re.compile(
            r"(?:квитанці[яю])|(?:скриншот.{0,10}(оплат|квитанц))|(?:фото.{0,10}(чеку|квитанц))|(?:чек.{0,10}(оплат|надішл|скинь))|(?:підтвердження.{0,10}оплати.{0,10}(надішл|скинь))|(?:screenshot.{0,5}of.{0,5}payment)|(?:\bпруф\b.{0,10}оплат)|(?:\bскрін\b.{0,5}(чек|оплат|квитанц))|(?:чек.{0,10}(оплат|надішл))|(?:пруф.{0,10}оплат)",
            re.IGNORECASE,
        ),
        10,
        "WARN",
        "Вимога квитанції — WARN рівень. Саме по собі не небезпечно, але може бути використано для відмови пі",
        suppress_hard=frozenset(),
        review_only=False,
    ),
]

SAFE_RULES: list[RegexRule] = [
    RegexRule(
        "GEN_F01_SAFE",
        "SAFE",
        re.compile(
            r"(?:без.{0,5}третіх.{0,5}осіб)|(?:не.{0,10}(від|приймаю.{0,5}від).{0,5}третіх)|(?:тільки.{0,5}(зі?|з).{0,5}своєї.{0,5}картк)|(?:тільки.{0,5}власник.{0,5}картк)|(?:дроп.{0,5}(заборонен|не\s*прийма|відмовлю))|(?:без.{0,5}посередників)|(?:не.{0,10}пишіть.{0,10}(у|в).{0,5}(telegram|tg|viber|whatsapp|телеграм|вайбер))|(?:в.{0,5}месенджери.{0,5}не.{0,5}переходжу)|(?:спілкування.{0,5}тільки.{0,5}(в\s*)?чаті.{0,5}біржі)|(?:тільки.{0,5}чат.{0,5}(біржі|платформи))|(?:не.{0,5}виходжу.{0,5}за.{0,5}межі)",
            re.IGNORECASE,
        ),
        -50,
        "SAFE",
        "Не ризикована — навпаки, захист від трикутника.",
        suppress_hard=frozenset({'TRIANGLE', 'THIRD_PARTY_HINT'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_F03_SAFE",
        "SAFE",
        re.compile(
            r"(?:не.{0,10}(бере|приймає).{0,10}від.{0,10}(третіх|чужих))|(?:тільки.{0,5}своїх.{0,5}реквізит)|(?:без\s*дропів)|(?:дропи.{0,5}не.{0,5}прийма)",
            re.IGNORECASE,
        ),
        -50,
        "SAFE",
        "Не ризикова — підтвердження що мерчант дотримується правил.",
        suppress_hard=frozenset({'TRIANGLE', 'THIRD_PARTY_HINT'}),
        review_only=True,  # review-only signal
    ),
    RegexRule(
        "GEN_SAFE_ANTI_EXT",
        "SAFE",
        re.compile(
            r"(?:не.{0,10}пишіть.{0,10}(у|в).{0,5}(telegram|tg|viber|whatsapp|signal|телеграм|вайбер))|(?:в.{0,5}месенджери.{0,5}не.{0,5}переходжу)|(?:спілкування.{0,5}тільки.{0,5}(в\s*)?чаті.{0,5}біржі)|(?:тільки.{0,5}чат.{0,5}(біржі|платформи))|(?:не.{0,5}виходжу.{0,5}за.{0,5}межі)|(?:chat.{0,5}only.{0,5}(on\s*)?platform)",
            re.IGNORECASE,
        ),
        -50,
        "SAFE",
        "Мерчант забороняє зовнішні месенджери",
        suppress_hard=frozenset({'EXTERNAL_LINK'}),
        review_only=False,
    ),
    RegexRule(
        "GEN_SAFE_ANTI_DROP",
        "SAFE",
        re.compile(
            r"(?:без.{0,5}третіх.{0,5}осіб)|(?:не.{0,10}(від|приймаю.{0,5}від).{0,5}третіх.{0,5}осіб)|(?:тільки.{0,5}(зі?|з).{0,5}своєї.{0,5}картк)|(?:лише.{0,5}(зі?|з).{0,5}своєї.{0,5}картк)|(?:тільки.{0,5}з.{0,5}особистої.{0,5}картк)|(?:оплата.{0,5}лише.{0,5}з.{0,5}картки.{0,5}власника)|(?:переказ.{0,5}тільки.{0,5}від.{0,5}власника)|(?:не.{0,5}приймаю.{0,5}від.{0,5}інших.{0,5}осіб)|(?:без.{0,5}посередників)|(?:тільки.{0,5}власник.{0,5}картки)|(?:дроп[иі]?.{0,5}(заборонен|не\s*прийма|відмовлю))|(?:без.{0,5}дропів)",
            re.IGNORECASE,
        ),
        -50,
        "SAFE",
        "Мерчант явно забороняє третіх осіб та дропів",
        suppress_hard=frozenset({'TRIANGLE', 'THIRD_PARTY_HINT'}),
        review_only=False,
    ),
]


ALL_RULES: list[RegexRule] = HARD_RULES + SOFT_RULES + WARN_RULES + SAFE_RULES


SUPPRESSOR_MAP: dict[str, frozenset] = {
    rule.category: rule.suppress_hard
    for rule in SAFE_RULES
    if rule.suppress_hard
}
