"""
tests/test_rules_generated.py
AUTO-GENERATED by build_rules.py

Покриває:
  - HARD правила: повинні давати BLOCK
  - SOFT правила: повинні накопичувати score > 0
  - SAFE suppressors: повинні скасовувати відповідний HARD
  - review_only правила: не повинні BLOCK, тільки score
  - False positive guards: амбігуозні короткі маркери не повинні блокувати чисті тексти
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import pytest
from rules import HARD_RULES, SOFT_RULES, SAFE_RULES, WARN_RULES, ALL_RULES


def _matches(rule, text: str) -> bool:
    return bool(rule.pattern.search(text.lower()))


def _first_hard(text: str):
    for r in HARD_RULES:
        if _matches(r, text):
            return r
    return None


def _soft_score(text: str) -> int:
    score = 0
    for r in SOFT_RULES:
        if _matches(r, text):
            score += r.weight
    return score


def _safe_suppresses(text: str, hard_category: str) -> bool:
    for r in SAFE_RULES:
        if hard_category in r.suppress_hard and _matches(r, text):
            return True
    return False


# ═══════════════════════════════════════════════════════
# HARD rules — повинні давати збіг
# ═══════════════════════════════════════════════════════

@pytest.mark.parametrize('category,text,expected', [
    ('EXTERNAL_LINK', 'пишіть мені у телеграм перед оплатою', True),
    ('EXTERNAL_LINK', 't.me/mychannel123', True),
    ('EXTERNAL_LINK', '@coolmerchant99 for details', True),
    ('TRIANGLE', 'оплата від знайомого вітається', True),
    ('TRIANGLE', 'дропи ок, можна переказувати', True),
    ('TRIANGLE', 'карта дружини підійде', True),
    ('NO_COMMENTS', 'без коментарів у переказі', True),
    ('NO_COMMENTS', 'поле залишіть пустим', True),
    ('NO_COMMENTS', 'нічого не пишіть у призначенні', True),
    ('CASINO', 'казино трафік приймаю', True),
    ('CASINO', '1xbet та melbet ок', True),
    ('CASINO', 'процесинг агрегатор', True),
    ('FINCRIME', 'обнал приймаю, ставка 5%', True),
    ('FINCRIME', 'грязні гроші без питань', True),
])
def test_hard_match(category, text, expected):
    matched = _first_hard(text)
    if expected:
        assert matched is not None, f'HARD miss: {repr(text)}'
        assert matched.category == category, f'Wrong category: {matched.category} != {category}'
    else:
        assert matched is None, f'Unexpected HARD match: {repr(text)}'


# ═══════════════════════════════════════════════════════
# SAFE suppressors — повинні скасовувати HARD
# ═══════════════════════════════════════════════════════

@pytest.mark.parametrize('hard_category,text', [
    ('TRIANGLE', 'без третіх осіб, тільки власник картки'),
    ('TRIANGLE', 'дропи заборонені, без посередників'),
    ('TRIANGLE', 'тільки зі своєї картки'),
    ('EXTERNAL_LINK', 'не пишіть у телеграм, тільки чат біржі'),
    ('EXTERNAL_LINK', 'в месенджери не переходжу'),
])
def test_safe_suppresses_hard(hard_category, text):
    assert _safe_suppresses(text, hard_category), \
        f'Suppressor miss for {hard_category}: {repr(text)}'


# ═══════════════════════════════════════════════════════
# SOFT rules — повинні накопичувати score > threshold
# ═══════════════════════════════════════════════════════

@pytest.mark.parametrize('text,min_score', [
    ('писати в лс до оплати', 20),
    ('рахунок фоп, iban фоп', 20),
    ('апеляцію відкрию якщо не платите', 20),
    ('анонімно, без зайвих питань', 20),
    ('посередник є, номінальний рахунок', 30),
    ('чардж зроблю якщо не відпустите', 30),
    ('фінмон не проблема, заморозка не наша вина', 30),
])
def test_soft_score(text, min_score):
    score = _soft_score(text)
    assert score >= min_score, \
        f'Score too low for {repr(text)}: {score} < {min_score}'


# ═══════════════════════════════════════════════════════
# False positive guard — чисті тексти НЕ повинні BLOCK
# ═══════════════════════════════════════════════════════

@pytest.mark.parametrize('text', [
    'тільки monobank та privatbank, верифікований мерчант',
    'не пишіть у telegram, спілкування тільки в чаті біржі',
    'без третіх осіб, тільки власник картки',
    'без посередників, без дропів, переказ тільки від власника',
    'оплата mono або приват, перевірений мерчант 500+ угод',
    'дропи не приймаю, відмовлю',
    'не виходжу за межі платформи',
    'тільки з особистої картки, без посередників',
])
def test_clean_text_no_hard_block(text):
    matched = _first_hard(text)
    assert matched is None, \
        f'False positive HARD on clean text: {repr(text)} → {matched}'


# ═══════════════════════════════════════════════════════
# review_only rules — ніколи не повинні бути в HARD_RULES
# ═══════════════════════════════════════════════════════

def test_review_only_not_in_hard():
    for r in HARD_RULES:
        assert not r.review_only, \
            f'review_only rule found in HARD_RULES: {r.id} ({r.category})'


# ═══════════════════════════════════════════════════════
# Sanity — всі патерни компілюються без помилок
# ═══════════════════════════════════════════════════════

def test_all_patterns_compile():
    for r in ALL_RULES:
        assert r.pattern is not None, f'None pattern in rule {r.id}'
        # Just try a match to ensure no runtime error
        try:
            r.pattern.search('test string')
        except Exception as e:
            pytest.fail(f'Pattern error in {r.id}: {e}')
